version: '3'
services:
  postgres:
    container_name: nest-pg
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - docker.env

volumes:
  db:
    driver: local
